{"uid":"8dada087a09d584b","name":"test_error_without_traceback","fullName":"test.utilities.test_cli.TestAlertFunctions#test_error_without_traceback","historyId":"3046a012cff151115e61e02786daf834","time":{"start":1756776344541,"stop":1756776344542,"duration":1},"description":"Verify error() logs at the ERROR level without a traceback.","descriptionHtml":"<p>Verify error() logs at the ERROR level without a traceback.</p>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"parentSuite","value":"test.utilities"},{"name":"suite","value":"test_cli"},{"name":"subSuite","value":"TestAlertFunctions"},{"name":"host","value":"dtc205659"},{"name":"thread","value":"538732-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test.utilities.test_cli"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"8dada087a09d584b.json","parameterValues":[]}
